name: Update README
on:
  push:
    branches:
      - master
  schedule:
    - cron: '*/30 0 * * *'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Update my blog posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "MYBLOG-POST-LIST"
          feed_list: "https://www.andrewconnell.com/blog/rss.xml"
          commit_message: "Update README with my latest blog posts"
          max_post_count: "5"
          date_format: "mmm d, yyyy"
          template: '$newline- $date - [$title]($url)'
      - name: Update Voitanos' blog posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://www.voitanos.io/index.xml"
          comment_tag_name: "VOITANOSBLOG-POST-LIST"
          commit_message: "Update README with Voitanos' latest blog posts"
          max_post_count: "5"
          date_format: "mmm d, yyyy"
          template: '$newline- $date - [$title]($url)'
      - name: Update Microsoft Cloud Show episodes
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://www.microsoftcloudshow.com/rss.xml"
          comment_tag_name: "MSCLOUDSHOWBLOG-POST-LIST"
          commit_message: "Update README with MSCLOUDSHOW's latest episodes"
          max_post_count: "5"
          date_format: "mmm d, yyyy"
          template: '$newline- $date - [$title]($url)'
